[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  external_node_modules = [
    "serverless-http",
    "@aws-sdk/client-s3",
    "@aws-sdk/client-polly",
    "@aws-sdk/s3-request-presigner",
    "express",
    "cors",
    "dotenv",
    "openai"
  ]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

